CREATE SCHEMA IF NOT EXISTS ZAMAZON;

USE ZAMAZON;

CREATE TABLE Productos (
  IdProducto INT PRIMARY KEY AUTO_INCREMENT,
  nombreProducto VARCHAR(40) NOT NULL,
  precio NUMERIC(7, 2) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  cantidad NUMERIC(5) NOT NULL,
  imagen VARCHAR(100) NOT NULL
);

CREATE TABLE USUARIOS (
  USUARIO VARCHAR(12) PRIMARY KEY NOT NULL,
  CONTRASENA VARCHAR(255) NOT NULL,
  FECHANACIMIENTO DATE NOT NULL
);

CREATE TABLE CESTAS (
  IDCESTA INT PRIMARY KEY AUTO_INCREMENT,
  USUARIO VARCHAR(12),
  PRECIOTOTAL NUMERIC(7, 2) NOT NULL DEFAULT(0),
  CONSTRAINT FK_CESTAS_USUARIOS FOREIGN KEY (USUARIO) REFERENCES USUARIOS(USUARIO)
);

CREATE TABLE PRODUCTOSCESTAS (
  IDPRODUCTO INT,
  IDCESTA INT,
  CANTIDAD NUMERIC(2),
  CONSTRAINT PK_PRODUCTOSCESTAS PRIMARY KEY (IDPRODUCTO, IDCESTA),
  CONSTRAINT FK_PRODUCTOSCESTAS_PRODUCTOS FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTOS(IDPRODUCTO),
  CONSTRAINT FK_PRODUCTOSCESTAS_CESTAS FOREIGN KEY (IDCESTA) REFERENCES CESTAS(IDCESTA)
);