CREATE SCHEMA IF NOT EXISTS zamazon;

USE zamazon;

CREATE TABLE Productos (
  IdProducto INT PRIMARY KEY AUTO_INCREMENT,
  nombreProducto VARCHAR(40) NOT NULL,
  precio NUMERIC(7, 2) NOT NULL,
  descripcion VARCHAR(255) NOT NULL,
  cantidad NUMERIC(5) NOT NULL,
  imagen VARCHAR(100) NOT NULL
);

CREATE TABLE usuarios (
  usuario VARCHAR(12) PRIMARY KEY NOT NULL,
  contrasena VARCHAR(255) NOT NULL,
  fechaNacimiento DATE NOT NULL,
  rol VARCHAR(10) NOT NULL DEFAULT('cliente'),
);

CREATE TABLE cestas (
  IdCestas INT PRIMARY KEY AUTO_INCREMENT,
  usuario VARCHAR(12),
  preciototal NUMERIC(7, 2) NOT NULL DEFAULT(0),
  CONSTRAINT FK_CESTAS_usuarios FOREIGN KEY (usuario) REFERENCES usuarios(usuario)
);

CREATE TABLE productosCestas (
  IdProducto INT,
  IdCesta INT,
  cantidad NUMERIC(2),
  CONSTRAINT PK_PRODUCTOSCESTAS PRIMARY KEY (IdProducto, IdCesta),
  CONSTRAINT FK_PRODUCTOSCESTAS_PRODUCTOS FOREIGN KEY (IdProducto) REFERENCES productos(IdProducto),
  CONSTRAINT FK_PRODUCTOSCESTAS_CESTAS FOREIGN KEY (IdCesta) REFERENCES cestas(IDCESTA)
);